server:
  port: 8081

spring:
  cassandra:
    keyspace-name: tasks
    username: ${ASTRA_USERNAME}
    password: ${ASTRA_PASSWORD}
    schema-action: none

datastax:
  astra:
    secure-connect-bundle: ${SECURE_CONNECT_BUNDLE}

    request:
      timeout: 10s

    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

  kafka:
    bootstrap-servers: 172.25.119.108:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      retries: 3
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
      linger-ms: 1

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true

  swagger-ui:
    display-request-duration: true
    groups-order: DESC

  group-configs:
    - group: Rest Controllers (Spring MVC)
      packages-to-scan: com.datastax.workshop


zookeeper:
  connect-string: localhost:2181
  leader-path: /scheduling-service/leader
  assignment-path: /scheduling-service/segments/assignments
  instances-path: /scheduling-service/instances
  session-timeout: 5000
  connection-timeout: 5000

task_schedule:
  total-segment: 100

app:
  kafka:
    topic: scheduling-topic

metadata:
  fetch:
    timeout:
      ms: 10000