spring:
  cassandra:
    keyspace-name: tasks
    username: ${ASTRA_USERNAME}
    password: ${ASTRA_PASSWORD}
    schema-action: none

datastax:
  astra:
    secure-connect-bundle: ${SECURE_CONNECT_BUNDLE}